### PR TITLE
Mobile-1713 choice: Changed choice results to use chart.js

### PR DESCRIPTION
**Pull request by HaakonBj**
Swapped the choice results in the app to using chart.js.
Unsure how to deal with the strings that are not being used anymore, some help on this would be appreciated.
Test:
1. Create a choice activity, allow the choices to be published.
2. Log in as students and vote on the choice activity. 
3. Log in as person who can see the results.

### CODE REVIEW

**Comment by moodlemobile** [comment]
Thanks for your contribution, we'll review this for our next release.

**Comment by jleyva** [comment]
Hi,
please can you tell us what is your user in the Moodle tracker so we can assign you https://tracker.moodle.org/browse/MOBILE-1713 and follow there the progress?

**Comment by HaakonBj** [comment]
Hey! 
Username is: Håkon

**Comment by jleyva** [comment]
Closing this pull request since we now follow a integration in a separate branch approach (we'll be integrating this to the integration branch), please see https://tracker.moodle.org/browse/MOBILE-1713 for more information

**Pull request closed without merging**
