### PR TITLE
MOBILE-1796 core: Updated to NodeJS v6.9.1

### PR DESCRIPTION
**Pull request by martinmine**
Supports building on NodeJS v6.9.1. 

Had to replace ionic plugin `cordova-plugin-local-notifications-mm` with `de.appplant.cordova.plugin.local-notification` in order to make it buildable, but they appear to be the same as the previous one was a fork of the original plugin. `de.appplant.cordova.plugin.local-notification` was also previously used.

### CODE REVIEW

**Comment by MELAS007** [comment]
Dear,

@martinmine - I must download first the master one then i modify these files right?

Regards,

**Comment by MELAS007** [comment]
@martinmine - i got errors on ionic serve

$ ionic serve

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.runr (C:\Users\MELAS\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:191:19)
    at C:\Users\MELAS\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:54:9
    at _fulfilled (C:\Users\MELAS\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\MELAS\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\MELAS\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\MELAS\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Users\MELAS\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Cannot read property 'hasOwnProperty' of undefined (CLI v2.1.7)

Your system information:

 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

**Comment by martinmine** [comment]
Clone the Overwork repo then checkout on the MOBILE-1796 branch. I'm getting the same error message as of yesterday on an isolated test environment. It might be related to a missing Android SDK, I will try it out more later tomorrow and get back to you.

**Comment by martinmine** [comment]
@MELAS007 you can try with Ionic CLI v. 2.1.1 as this is currently working fine on my setup. Run `npm install ionic@2.1.1` then run `ionic state restore` again. This seems to be a known issue with [Ionic CLI.](https://github.com/driftyco/ionic-cli/issues/1648)

**Comment by MELAS007** [comment]
@martinmine - I am trying now and I will let you know

Thanks

**Comment by MELAS007** [comment]
@martinmine - Thank you very much, It works. but I have a question : why cordova icons isn't changed to my icons... i did "ionic resources" it changed all and also in config.xml is with the correct path but it is still cordova icons...
Could you tell me how can i do this?

**Comment by martinmine** [comment]
@MELAS007 you should ask somewhere else as this thread is for this pull request, not upgrading to Firebase from GCM. I advice you to look around on Google's resources and StackOverflow for advice on this.

**Comment by MELAS007** [comment]
Hi Martin,

 I have ionic version 2.1.17, npm 4.0.5 and node 6.9.2 . It doesn't work...


$ cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
Path: platforms\android
Package: com.moodle.moodlemobile
Name: Moodle_Mobile
Activity: MainActivity
Android target: android-24
Subproject Path: CordovaLib
Android project created with cordova-android@6.0.0
Running command: "C:\Program Files (x86)\nodejs\node.exe" "D:\Mobile
apps\moodlemobile2-3.1.3\hooks\after_prepare\010_add_platform_class.js"
"D:/Mobile apps/moodlemobile2-3.1.3"
add to body class: platform-android
Running command: "C:\Program Files (x86)\nodejs\node.exe" "D:\Mobile
apps\moodlemobile2-3.1.3\hooks\after_prepare\020_add_ios_transport_security.js"
"D:/Mobile apps/moodlemobile2-3.1.3"
module.js:471
throw err;
^

Error: Cannot find module 'plist'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (D:\Mobile
apps\moodlemobile2-3.1.3\hooks\after_prepare\020_add_ios_transport_security.js:10:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
Error: Hook failed with error code 1: D:\Mobile
apps\moodlemobile2-3.1.3\hooks\after_prepare\020_add_ios_transport_security.js

and in ionic serve -l got blank !

any help will be appreciated

MELAS007

**Comment by martinmine** [comment]
@MELAS007 did you apply the version change for appium as specified in [this](https://github.com/moodlehq/moodlemobile2/pull/709) pr?

**Comment by MELAS007** [comment]
Sorry I don't understand what you mean?

**Comment by martinmine** [comment]
Apply the changes in the pull request I linked, then clean and try build the project again.

**Comment by MELAS007** [comment]
Where is the link?

**Comment by martinmine** [comment]
I already linked the PR in my previous comment... However, I will leave it [here](https://github.com/moodlehq/moodlemobile2/pull/709) as it may be a bit hard to see the links on GitHub.

**Comment by MELAS007** [comment]
Thanks but I am not using appium...

**Comment by MELAS007** [comment]
@martinmine - i got errors after modifying this: <1.6.0 to appium.
MELAS@MELAS-PC MINGW64 /d/Mobile apps/moodlemobile2-3.2.0
$ npm install
npm WARN package.json mm2@1.0.0 No repository field.
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.9.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: appium@'^1.4.11<1.6.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.0.14","0.0.15","0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.2.3","0.3.0","0.3.1","0.4.0","0.4.1","0.5.0","0.5.1","0.5.2","0.6.0","0.6.1","0.7.0","0.7.1","0.7.2","0.7.3","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.9.0","0.9.1","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.11.0","0.11.1","0.11.2","0.11.3","0.11.4","0.12.0","0.12.1-b","0.12.2","0.12.3","0.13.0","0.14.0","0.14.1","0.14.2","0.15.0","0.16.0","0.17.0","0.17.2","0.17.3","0.17.4","0.17.5","0.17.6","0.18.0","0.18.1","1.0.0-beta.1","0.18.2","1.0.0-beta.2","1.0.0","1.1.0","1.2.0","1.2.1","1.2.2","1.2.3","1.3.0-beta1","1.2.4","1.3.0","1.3.1","1.3.2-beta2","1.3.3","1.3.4-beta1","1.3.4","1.3.5-beta","1.3.5","1.3.6","1.3.7","1.4.0-beta","1.4.0","1.4.1","1.4.2","1.4.3-beta","1.4.3","1.4.4","1.4.5-beta","1.4.5","1.4.6-beta","1.4.6-beta2","1.4.6","1.4.7-beta","1.4.7-beta2","1.4.7-beta3","1.4.7","1.4.8-beta","1.4.8","1.4.9-beta","1.4.10","1.5.0-beta1","1.5.0-beta2","1.5.0-beta3","1.4.11","1.5.0-beta4","1.5.0-beta5","1.4.12","1.4.13","1.5.0-beta6","1.5.0-beta7","1.4.14","1.4.15","1.4.16","1.5.0-beta11","1.5.0-beta12","1.5.0-beta13","1.5.0-beta14","1.5.0-beta15","1.5.0-beta16","1.5.0","1.5.1","1.5.2","1.5.3","1.6.0-beta1","1.6.0-beta2","1.6.0-beta3","1.6.0","1.6.1-beta","1.6.1","1.6.2","1.6.3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'mm2'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Mobile apps\moodlemobile2-3.2.0\npm-debug.log

what can i do?

**Comment by MELAS007** [comment]
@martinmine - i got errors after modifying this package.json file :
$ npm install
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: appium@^1.4.11<1.6.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.6.3, 1.6.2, 1.6.1, 1.6.1-beta, 1.6.0, 1.6.0-beta3, 1.6.0-beta2, 1.6.0-beta1, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.5.0-beta7, 1.5.0-beta6, 1.5.0-beta5, 1.5.0-beta4, 1.5.0-beta3, 1.5.0-beta2, 1.5.0-beta16, 1.5.0-beta15, 1.5.0-beta14, 1.5.0-beta13, 1.5.0-beta12, 1.5.0-beta11, 1.5.0-beta1, 1.4.16, 1.4.15, 1.4.14, 1.4.13, 1.4.12, 1.4.11, 1.4.10, 1.4.9-beta, 1.4.8, 1.4.8-beta, 1.4.7, 1.4.7-beta3, 1.4.7-beta2, 1.4.7-beta, 1.4.6, 1.4.6-beta2, 1.4.6-beta, 1.4.5, 1.4.5-beta, 1.4.4, 1.4.3, 1.4.3-beta, 1.4.2, 1.4.1, 1.4.0, 1.4.0-beta, 1.3.7, 1.3.6, 1.3.5, 1.3.5-beta, 1.3.4, 1.3.4-beta1, 1.3.3, 1.3.2-beta2, 1.3.1, 1.3.0, 1.3.0-beta1, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.0, 1.0.0-beta.2, 1.0.0-beta.1, 0.18.2, 0.18.1, 0.18.0, 0.17.6, 0.17.5, 0.17.4, 0.17.3, 0.17.2, 0.17.0, 0.16.0, 0.15.0, 0.14.2, 0.14.1, 0.14.0, 0.13.0, 0.12.3, 0.12.2, 0.12.1-b, 0.12.0, 0.11.4, 0.11.3, 0.11.2, 0.11.1, 0.11.0, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.1, 0.9.0, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.4.1, 0.4.0, 0.3.1, 0.3.0, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'mm2'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Mobile apps\moodlemobile2-3.2.0\npm-debug.log

what can i do?

**Comment by MELAS007** [comment]
@martinmine - i did ionic state restore , it works but many errors in console logs see in attached.
image

**Comment by MELAS007** [comment]
@martinmine - Plz help ! I did what you said but it is not working!

**Comment by jleyva** [comment]
Closing this as it has been already implemented. See https://tracker.moodle.org/browse/MOBILE-1796 for more information.

**Comment by MELAS007** [comment]
@martinmine @jleyva - PLEASE REMIND ME WHICH VERSION DO YOU USE FOR NODE AND IONIC 2?

**Pull request closed without merging**
